### ISSUE TITLE
[Question] - Deezer2Spotify?

### ISSUE THREAD

**Issue by Jorman** [humpherson/Spotify2Deezer#1]
Hi, I'm just looking for a way to transfer my playlist though from Deezer -> Spotify
Are you by any chance going to develop, or do you know where I can find this variant?

Thanks

J

**Comment by humpherson** [comment]
I gave up and found [tunemymusic](https://www.tunemymusic.com/transfer/deezer-to-spotify), it's free, intuitive and works really well.

**Comment by Jorman** [comment]
Oh, thank you for the suggestion!
